compressionLevel: mixed

enableGlobalCache: false

packageExtensions:
  "@aws-sdk/core@*":
    dependencies:
      tslib: "*"
  local-pkg@*:
    dependencies:
      happy-dom: ^12.5.0
  react-intersection-observer@*:
    dependencies:
      react-dom: "*"
  swiper@*:
    dependencies:
      react: ^18.0.2

yarnPath: .yarn/releases/yarn-4.2.2.cjs
